import type { Metadata } from "next";
import { Sora } from "next/font/google";

const inter = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Post Details | Blogging App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
