
import type { Metadata } from "next";
import { Mooli } from "next/font/google";
import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import Link from "next/link";

const inter = Mooli({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
	title: "Home | Neon Blog",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={inter.className}>
					<nav className='w-full py-4 border-b-[1px] md:px-8 px-4 text-center flex items-center justify-between sticky top-0 bg-white z-10 '>
						<Link href='/' className='text-xl font-extrabold text-blue-700'>
							Neon Blog
						</Link>

						<div className='flex items-center gap-5'>
							
							<SignedOut>
								<SignInButton mode="modal"/>
							</SignedOut>
							<SignedIn>
								<Link href='/posts/create' className=''>
							Create Post
								</Link>
								<UserButton showName/>
							</SignedIn>
						</div>
					</nav>

					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}